# Generated by Django 3.1.1 on 2020-09-27 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Message',
        ),
    ]
