# Generated by Django 3.1.1 on 2020-09-26 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kurs', models.FloatField()),
                ('kurs_date', models.DateTimeField(null=True, verbose_name='date')),
            ],
        ),
    ]
