# Generated by Django 3.1.1 on 2020-09-27 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataproject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataproject',
            name='company',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
