# Generated by Django 3.1.1 on 2020-09-27 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200925_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='voters_comment',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
